# Generated by Django 5.2.15 on 2026-06-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='pin_hash',
        ),
    ]
