# Generated by Django 5.2.15 on 2026-06-11 20:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('institutions', '0001_initial'),
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clock_out_at', models.DateTimeField(blank=True, null=True)),
                ('actual_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('credited_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('roll', models.CharField(blank=True, max_length=50)),
                ('clock_in_photo', models.ImageField(upload_to='attendance_audit/')),
                ('clock_out_photo', models.ImageField(blank=True, null=True, upload_to='attendance_audit/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.unit')),
            ],
            options={
                'ordering': ['-clock_in_at'],
                'indexes': [models.Index(fields=['trainer', 'is_active'], name='attendance__trainer_840798_idx'), models.Index(fields=['unit', 'clock_in_at'], name='attendance__unit_id_0495c6_idx')],
            },
        ),
    ]
